from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Tuple
import argparse
import math
import random
import sys
import time


Vertex = int
Edge = Tuple[int, int]


@dataclass
class Result:
    graph_name: str
    algorithm: str
    labels: Dict[Vertex, int]
    edge_weights: Dict[Edge, int]
    k: int
    lower_bound: int
    gap: int
    gap_ratio: float
    valid: bool
    runtime: float
    status: str
    best_strategy: str


class MusicalGraph:
    """
    Formula-based 5-regular musical graph C_{n,2}.

    Vertices:
      inner_i -> i
      outer_i -> n+i

    The graph topology is generated by formulas instead of a permanent
    adjacency matrix or stored edge list.
    """

    def __init__(self, n: int):
        if n < 3:
            raise ValueError("C_{n,2} needs n >= 3.")
        self.n = n
        self.name = f"C_{{{n},2}}"
        self.V = 2 * n
        self.E = 5 * n
        self.delta = 5
        self._validate_topology()

    def inner(self, i: int) -> int:
        return i % self.n

    def outer(self, i: int) -> int:
        return self.n + (i % self.n)

    def vertices(self) -> List[Vertex]:
        return list(range(self.V))

    def neighbors(self, v: Vertex) -> List[Vertex]:
        n = self.n
        if 0 <= v < n:
            i = v
            return [
                self.inner(i - 1),
                self.inner(i + 1),
                self.outer(i - 1),
                self.outer(i),
                self.outer(i + 1),
            ]
        if n <= v < 2 * n:
            i = v - n
            return [
                self.outer(i - 1),
                self.outer(i + 1),
                self.inner(i - 1),
                self.inner(i),
                self.inner(i + 1),
            ]
        raise ValueError(f"Invalid vertex: {v}")

    def edges(self) -> Iterable[Edge]:
        seen = set()

        def add(u: Vertex, v: Vertex):
            edge = tuple(sorted((u, v)))
            if edge not in seen:
                seen.add(edge)
                return edge
            return None

        for i in range(self.n):
            for edge in (
                add(self.inner(i), self.inner(i + 1)),
                add(self.outer(i), self.outer(i + 1)),
                add(self.inner(i), self.outer(i)),
                add(self.inner(i), self.outer(i - 1)),
                add(self.inner(i), self.outer(i + 1)),
            ):
                if edge is not None:
                    yield edge

    def _validate_topology(self) -> None:
        edge_set = set(self.edges())
        assert len(edge_set) == self.E, f"Edge count error: expected {self.E}, got {len(edge_set)}"
        for v in self.vertices():
            assert len(set(self.neighbors(v))) == 5, f"Degree error at vertex {v}"


def lower_bound(graph: MusicalGraph) -> int:
    return max(math.ceil((graph.E + 1) / 2), graph.delta)


def validate_labeling(graph: MusicalGraph, labels: Dict[Vertex, int], store: bool = True):
    if len(labels) != graph.V:
        return False, {}, "Missing labels."
    if min(labels.values()) < 1:
        return False, {}, "Labels must be positive."
    used = set()
    edge_weights = {}
    for edge in graph.edges():
        u, v = edge
        w = labels[u] + labels[v]
        if w in used:
            return False, edge_weights, f"Duplicate edge weight found: {w}"
        used.add(w)
        if store:
            edge_weights[edge] = w
    if len(used) != graph.E:
        return False, edge_weights, "Unique edge count does not match E."
    return True, edge_weights, "All edge weights are unique."


def candidate_orders(graph: MusicalGraph, restarts: int) -> List[Tuple[str, List[Vertex]]]:
    n = graph.n
    inner = [graph.inner(i) for i in range(n)]
    outer = [graph.outer(i) for i in range(n)]
    alternating = []
    zigzag = []
    for i in range(n):
        alternating.extend([graph.inner(i), graph.outer(i)])
        zigzag.extend([graph.inner(i), graph.outer(i + 1)])
    orders = [
        ("inner_then_outer", inner + outer),
        ("outer_then_inner", outer + inner),
        ("alternating", alternating),
        ("reverse_alternating", list(reversed(alternating))),
        ("zigzag", zigzag),
    ]
    for seed in range(restarts):
        rng = random.Random(51000 + seed)
        order = graph.vertices()
        rng.shuffle(order)
        orders.append((f"random_seed_{51000 + seed}", order))
    return orders


def greedy_one_order(graph: MusicalGraph, order: List[Vertex], label_cap: int):
    labels: Dict[Vertex, int] = {}
    used_weights = set()
    for v in order:
        labeled_neighbors = [u for u in graph.neighbors(v) if u in labels]
        chosen = None
        for x in range(1, label_cap + 1):
            local = set()
            ok = True
            for u in labeled_neighbors:
                w = x + labels[u]
                if w in used_weights or w in local:
                    ok = False
                    break
                local.add(w)
            if ok:
                chosen = x
                break
        if chosen is None:
            return None
        labels[v] = chosen
        for u in labeled_neighbors:
            used_weights.add(chosen + labels[u])
    valid, _, _ = validate_labeling(graph, labels, store=False)
    return labels if valid else None


def exact_search(graph: MusicalGraph, cap: int, seconds: float):
    deadline = time.time() + seconds
    order = []
    for i in range(graph.n):
        order.extend([graph.inner(i), graph.outer(i)])
    labels: Dict[Vertex, int] = {}
    used_weights = set()

    def dfs(pos: int):
        if time.time() > deadline:
            return None
        if pos == len(order):
            valid, _, _ = validate_labeling(graph, labels, store=False)
            return dict(labels) if valid else None
        v = order[pos]
        labeled_neighbors = [u for u in graph.neighbors(v) if u in labels]
        for x in range(1, cap + 1):
            local = set()
            new_weights = []
            ok = True
            for u in labeled_neighbors:
                w = x + labels[u]
                if w in used_weights or w in local:
                    ok = False
                    break
                local.add(w)
                new_weights.append(w)
            if not ok:
                continue
            labels[v] = x
            for w in new_weights:
                used_weights.add(w)
            found = dfs(pos + 1)
            if found is not None:
                return found
            for w in new_weights:
                used_weights.remove(w)
            del labels[v]
        return None

    return dfs(0)


def cap_schedule(lb: int) -> List[int]:
    caps = []
    for multiplier in [1.0, 1.03, 1.06, 1.1, 1.2, 1.35, 1.5, 2.0]:
        cap = max(lb, math.ceil(lb * multiplier))
        if cap not in caps:
            caps.append(cap)
    return caps


def local_repair_search(
    graph: MusicalGraph,
    cap: int,
    attempts: int = 8,
    iterations: int = 1600,
    max_candidates: int = 160,
    time_limit: float = 10.0,
):
    deadline = time.time() + time_limit
    vertices = graph.vertices()
    edges = list(graph.edges())
    incident = {v: [] for v in vertices}
    for idx, (u, v) in enumerate(edges):
        incident[u].append(idx)
        incident[v].append(idx)

    for attempt in range(attempts):
        if time.time() > deadline:
            return None
        rng = random.Random(91000 + attempt + cap * 997)
        labels = {v: rng.randint(1, cap) for v in vertices}
        edge_weights = []
        counts = {}
        for u, v in edges:
            w = labels[u] + labels[v]
            edge_weights.append(w)
            counts[w] = counts.get(w, 0) + 1
        penalty = sum(c - 1 for c in counts.values() if c > 1)

        for _ in range(iterations):
            if time.time() > deadline:
                return None
            if penalty == 0:
                valid, _, _ = validate_labeling(graph, labels, store=False)
                return dict(labels) if valid else None
            bad_edges = [idx for idx, w in enumerate(edge_weights) if counts[w] > 1]
            bad_edge = rng.choice(bad_edges)
            a, b = edges[bad_edge]
            v = a if rng.random() < 0.5 else b
            current = labels[v]

            if cap <= max_candidates:
                values = list(range(1, cap + 1))
                rng.shuffle(values)
            else:
                values = {current, 1, cap}
                while len(values) < max_candidates:
                    values.add(rng.randint(1, cap))
                values = list(values)
                rng.shuffle(values)

            best_values = []
            best_penalty = None
            for x in values:
                touched = set()
                deltas = []
                for edge_idx in incident[v]:
                    u, wv = edges[edge_idx]
                    other = wv if u == v else u
                    old_weight = edge_weights[edge_idx]
                    new_weight = x + labels[other]
                    if old_weight == new_weight:
                        continue
                    touched.add(old_weight)
                    touched.add(new_weight)
                    deltas.append((old_weight, new_weight))
                old_local = sum(max(0, counts.get(w, 0) - 1) for w in touched)
                temp_counts = {w: counts.get(w, 0) for w in touched}
                for old_weight, new_weight in deltas:
                    temp_counts[old_weight] -= 1
                    temp_counts[new_weight] = temp_counts.get(new_weight, 0) + 1
                new_local = sum(max(0, c - 1) for c in temp_counts.values())
                candidate_penalty = penalty - old_local + new_local
                if best_penalty is None or candidate_penalty < best_penalty:
                    best_penalty = candidate_penalty
                    best_values = [x]
                    if best_penalty == 0:
                        break
                elif candidate_penalty == best_penalty:
                    best_values.append(x)

            chosen = rng.choice(best_values)
            labels[v] = chosen
            for edge_idx in incident[v]:
                u, wv = edges[edge_idx]
                other = wv if u == v else u
                old_weight = edge_weights[edge_idx]
                new_weight = chosen + labels[other]
                if old_weight == new_weight:
                    continue
                counts[old_weight] -= 1
                if counts[old_weight] == 0:
                    del counts[old_weight]
                counts[new_weight] = counts.get(new_weight, 0) + 1
                edge_weights[edge_idx] = new_weight
            penalty = best_penalty if best_penalty is not None else penalty
    return None


def is_prime(x: int) -> bool:
    if x < 2:
        return False
    if x % 2 == 0:
        return x == 2
    r = int(math.sqrt(x))
    for d in range(3, r + 1, 2):
        if x % d == 0:
            return False
    return True


def next_prime(x: int) -> int:
    y = max(2, x)
    while not is_prime(y):
        y += 1
    return y


def sidon_backup_labels(graph: MusicalGraph) -> Dict[Vertex, int]:
    p = next_prime(graph.V + 1)
    return {v: 2 * p * v + ((v * v) % p) + 1 for v in graph.vertices()}


def solve(graph: MusicalGraph, restarts: int = 20, exact_seconds: float = 0.25) -> Result:
    start = time.time()
    lb = lower_bound(graph)
    best_labels = None
    best_k = None
    best_strategy = None

    if graph.V <= 14:
        for cap in range(lb, lb + 12):
            labels = exact_search(graph, cap, exact_seconds)
            if labels is not None:
                best_labels = labels
                best_k = max(labels.values())
                best_strategy = f"bounded_dfs_cap_{cap}"
                break

    if graph.V <= 160:
        attempts = 8 if graph.V <= 80 else 4
        time_limit = 10.0 if graph.V <= 80 else 6.0
        for cap in cap_schedule(lb):
            labels = local_repair_search(graph, cap, attempts=attempts, time_limit=time_limit)
            if labels is None:
                continue
            k = max(labels.values())
            if best_k is None or k < best_k:
                best_labels = labels
                best_k = k
                best_strategy = f"local_repair_cap_{cap}"
                break

    if graph.V <= 120:
        cap = max(lb * 3 + 20, (best_k or lb) + 20)
        for strategy, order in candidate_orders(graph, restarts):
            labels = greedy_one_order(graph, order, cap)
            if labels is None:
                continue
            k = max(labels.values())
            if best_k is None or k < best_k:
                best_labels = labels
                best_k = k
                best_strategy = strategy

    if best_labels is None:
        best_labels = sidon_backup_labels(graph)
        best_k = max(best_labels.values())
        best_strategy = "sidon_backup_after_heuristic_failure"

    valid, edge_weights, _ = validate_labeling(graph, best_labels)
    runtime = time.time() - start
    gap = best_k - lb
    return Result(
        graph_name=graph.name,
        algorithm="Formula-neighbor DFS + local repair + multi-start greedy",
        labels=best_labels,
        edge_weights=edge_weights,
        k=best_k,
        lower_bound=lb,
        gap=gap,
        gap_ratio=round(best_k / lb, 6),
        valid=valid,
        runtime=runtime,
        status=(
            "Sidon backup only; not an optimized result"
            if best_strategy == "sidon_backup_after_heuristic_failure"
            else "Valid heuristic upper bound; optimality is not claimed"
        ),
        best_strategy=best_strategy or "unknown",
    )


def print_result(graph: MusicalGraph, result: Result, max_items: int = 20) -> None:
    print(f"\nGraph: {result.graph_name}")
    print(f"Algorithm: {result.algorithm}")
    print(f"Strategy: {result.best_strategy}")
    print(f"Status: {result.status}")
    print(f"|V|={graph.V}, |E|={graph.E}, Delta={graph.delta}, lower_bound={result.lower_bound}")
    print(f"k={result.k}, gap={result.gap}, gap_ratio={result.gap_ratio}, valid={result.valid}")
    print(f"runtime={result.runtime:.6f}s")
    print("Sample labels:", dict(list(sorted(result.labels.items()))[:max_items]))
    print("Sample edge weights:", dict(list(sorted(result.edge_weights.items()))[:max_items]))


def prompt_int(name: str, default: int, minimum: int = 1) -> int:
    while True:
        try:
            raw = input(f"Enter {name} [{default}]: ").strip()
        except EOFError:
            return default
        if not raw:
            return default
        try:
            value = int(raw)
            if value < minimum:
                print(f"{name} must be >= {minimum}.")
                continue
            return value
        except ValueError:
            print("Please enter an integer.")


def pause_before_exit() -> None:
    try:
        input("\nPress Enter to exit...")
    except EOFError:
        pass


def main() -> None:
    if len(sys.argv) == 1:
        print("5-Regular Musical Graph C_{n,2} Solver")
        print("Press Enter to use the default value shown in brackets.")
        n = prompt_int("n", 8, minimum=3)
        restarts = prompt_int("random restarts", 20, minimum=0)
        graph = MusicalGraph(n)
        result = solve(graph, restarts=restarts)
        print_result(graph, result)
        pause_before_exit()
        return

    parser = argparse.ArgumentParser(description="5-regular musical graph C_{n,2} solver.")
    parser.add_argument("n", type=int, nargs="?", default=8)
    parser.add_argument("--restarts", type=int, default=20)
    args = parser.parse_args()

    graph = MusicalGraph(args.n)
    result = solve(graph, restarts=args.restarts)
    print_result(graph, result)


if __name__ == "__main__":
    main()
